### ISSUE TITLE
Ukol1

### ISSUE THREAD

**Issue by KarolinaCastro** [KarolinaCastro/Python2022#1]
https://github.com/KarolinaCastro/Python2022/blob/master/Ukol1.py

**Comment by pixelneo** [comment]
Ahoj, funguje to, ukol mas splneny, ale mam par pripominek:
- Ty dve podmink(`if baliky[Balik] == True:` a `if baliky[Balik] == False:`). Pokud se nesplni ta prvni, tak se musi vyzkouset jestli je splnena ta druha... Slo by to jednoduseji (napoveda: `else`).
- Nazvy promennych je vhodne pojmenovavat malymi pismeny (`Balik` -> `balik`).

Mej se.
